---
title: "Coverage evaluation"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readr)
library(purrr)
library(dplyr)
library(stringr)
```

# Setup

```{r, message = FALSE, warning = FALSE, eval=FALSE}
cov_detail <- 
  list.files(here::here("data/raw_data/coverage/"),
             pattern = ".detail.csv",
             full.names = TRUE) %>% 
  purrr::set_names(~ str_extract(., "(?<=/)[[:digit:]]+(?=\\.DOC)")) %>%  
  purrr::map_dfr(~ read_table2(.x, col_names = TRUE), .id = "lab_id") %>% 
  dplyr::mutate(lab_id = as.numeric(lab_id))

```

```{r, message = FALSE, warning = FALSE, eval=FALSE}
write_rds(cov_detail, here::here("data/derived_data/coverage/cov_detail.rds"))
```

```{r}
animal_table <-
  read_rds("~/googledrive/research_extension/hair_shed/data/derived_data/animal_table.rds")
```

```{r}
sorted <- read_rds(here::here("data/derived_data/categorizing/sorted.sample_metadata.rds"))
```

```{r}
sorted_cov <-
  sorted %>% 
  select(lab_id, species, continent, region, population) %>% 
  left_join(cov_detail) 
```

```{r}
sample_table <-
  read_delim(
    "~/googledrive/research_extension/hair_shed/data/raw_data/200501_sample_sheet.csv",
    delim = c(","),
    col_names = TRUE,
    guess_max = 10000
  )
```
```{r}
sorted %<>%
  left_join(animal_table %>%
              select(lab_id = Lab_ID, international_id) %>%
              distinct()) 


sorted %<>% 
  mutate(
    international_id = 
      case_when(
        lab_id == 20076 ~ "UMCUSAM000000020076",
        lab_id == 20079 ~ "UMCUSAM000000020079",
        lab_id == 20098 ~ "UMCUSAM000000020098",
        lab_id == 20136 ~ "UMCUSAM000000020136",
        lab_id == 185723 ~ "CPC98_Bprimigenius_EnglandDerbyshire_5936", 
        
      )
  )
```


```{r}
depth <-
  read_table2(here::here("data/derived_data/joint_genotyping/filter_eval/filter_eval.with_indels.28.idepth"), skip = 1, col_names = c("international_id", "n_sites", "mean_depth"))
  
```
```{r}
sorted %>% 
filter(!international_id %in% depth$international_id) %>% 
  arrange(lab_id) %>% 
  View

```

```{r}
depth %>% 
  filter(!international_id %in% sorted$international_id) %>% 
  left_join(animal_table %>% 
              select(international_id, lab_id = Lab_ID, BC, Sex)) %>% 
  arrange(lab_id)
```


# Add to sample metadata

```{r}
cov_detail %>% 
  filter(!chr %in% c("X", "Y", "MT", "UNMAPPED")) %>% 
  group_by(lab_id) %>% 
  summarise(avg_coverage = mean(mean)) %>% 
  ungroup() %>% 
  right_join(sorted) %>%
```

```{r}
sa
```



# Incorrect sex issues?

```{r}
cov_detail %>% 
  filter(!chr %in% c("MT", "UNMAPPED")) %>% 
  filter(chr == "Y" & mean < 0.3)
```


```{r}
cov_detail %>% 
  filter(chr == "Y" & str_detect(sid, "(?<=^[[:upper:]]{6})F")) %>% 
  rename(Lab_ID = lab_id) %>% 
  select(Lab_ID:mean) %>% 
  left_join(animal_table) %>% 
  arrange(desc(mean))
```

# Autosomal coverage for all samples

## Plot

```{r, fig.width=10, fig.height=7}
sorted %>% 
  select(lab_id, species, continent, region, population) %>% 
  left_join(cov_detail) %>% 
  filter(species %in% c("bos taurus", "bos indicus")) %>% 
  rename(mean_cov = mean) %>% 
  filter(!is.na(chr)) %>% 
  filter(!chr %in%  c("MT", "UNMAPPED", "X", "Y")) %>% 
  ggplot(aes(y = forcats::fct_inorder(chr),
             # Orders `sid` (individuals) by lowest to highest
             # autosome-wide avg coverage (avg of all values in `mean_cov`)
             x = forcats::fct_reorder(sid, mean_cov, mean),
             fill = mean_cov)) +
  geom_tile() +
  viridis::scale_fill_viridis(option = "inferno", direction = -1) +
  labs(y = "Chromosome",
       x = "Sample",
       fill = "Mean coverage",
       title = "Cattle samples") +
  theme(
    axis.text.y = element_text(size = 12),
    axis.text.x = element_blank(),
    axis.ticks = element_blank(),
    axis.title.x = element_text(size = 20),
    axis.title.y = element_text(size = 20),
    legend.text = element_text(size = 12), 
    legend.title = element_text(size = 14),
    plot.title = element_text(size = 22)
  )

#ggsave(here::here("figures/cattle.cov_detail_flip.png"), width = 10, height = 7, dpi = 500)
```



# Chromosomes with poor coverage

```{r}
sorted_cov %>%
  filter(!chr %in%  c("MT", "UNMAPPED", "X", "Y")) %>%
  filter(!is.na(chr)) %>%
  group_by(lab_id, species, continent, region, population) %>%
  summarise(cov_gw = mean(mean)) %>%
  left_join(sorted_cov %>%
              filter(chr == 25) %>%
              select(lab_id, cov_25 = mean)) %>% 
  mutate(diff = cov_25 - cov_gw) %>% 
  arrange(diff)
  


```

```{r}
sorted_cov %>%
  filter(!chr %in%  c("MT", "UNMAPPED", "X", "Y")) %>%
  select(lab_id:population, chr, chr_cov = mean) %>% 
  group_by(lab_id) %>% 
  mutate(gw_cov = mean(chr_cov)) %>% 
  ungroup() %>% 
  mutate(diff = chr_cov - gw_cov) %>% 
  filter(chr == "18") %>% 
  arrange(desc(diff))
```

