---
title: "fastStructure"
author: "Harly Durbin"
output:
  html_document:
    df_print: paged
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
library(readr)
library(dplyr)
library(stringr)
library(magrittr)
library(purrr)
library(tidyr)
library(tidylog)
```

# Notes & questions

* In order to [install via conda](https://bioconda.github.io/recipes/plink_qc/README.html), need a Python 2.7 environment, which means you can't run Snakemake

---

```{r}
sample_metadata %>% 
  filter(international_id == "CPC98_Bprimigenius_EnglandDerbyshire_5936") %>% 
  mutate(fid = international_id,
         newid = "ancient_derbyshire",
         newfid = "ancient_derbysire") %>% 
  select(international_id, fid, newid, newfid) %>% 
  write_tsv(here::here("data/derived_data/plink_qc/update_ids.txt"), col_names = FALSE)
```


## Dataset key

* Which samples

```{r}
tibble::tribble(
  ~ Name, ~ Description, ~ `k ran`,
  "full", "All species. All available samples.", "1-20",
  "20all", "All species. Up to 20 (ranked by coverage) samples per population label.", "1-20",
  "20cattle", "Bos taurus, B.indicus, B. primigenius, composite. Up to 20 (ranked by coverage) samples per population label.", "1-20",
  "5cattle", "Bos taurus, B.indicus, B. primigenius, composite. Up to 5 (ranked by coverage) samples per population label.", "1-20",
  "5taurine", "Bos taurus, B. primigenius. Up to 5 (ranked by coverage) samples per population label.", "1-20",
  "allyak", "B. grunniens and B. mutus. All available samples.", "1-10",
  "allgayalgaur", "B. frontalis and B. gaurus. All available samples.", "1-10",
  "allbanteng", "B. javanicus. All available samples.", "1-8"
)
```

* Thinning parameter

```{r}
tibble::tribble(
  ~ Name, ~ Description,
  "superthin", "Randomly retain 0.001% of SNPs from each chromosome"
)
```

# Setup

```{r}
sample_metadata <- 
  read_csv(here::here("data/derived_data/metadata/bovine_demo.sample_metadata.csv")) %>% 
  mutate(international_id = if_else(international_id == "CPC98_Bprimigenius_EnglandDerbyshire_5936", "ancient_derbyshire", international_id))
```

## Dataset creation

```{r}
sample_metadata %>% 
  group_by(species) %>% 
  tally(sort = TRUE)
```

### `20all`

```{r}
sample_metadata %>% 
  group_by(population) %>% 
  top_n(20, avg_coverage) %>% 
  ungroup() %>% 
  mutate(fid = international_id) %>% 
  select(international_id, fid) %>% 
  write_tsv(here::here("data/derived_data/plink_qc/thin_variants/keeplist.20all.txt"), col_names = FALSE)
```

### `20cattle`

```{r}
sample_metadata %>% 
  filter(species %in% c("bos primigenius", "bos taurus", "composite", "bos indicus")) %>% 
  group_by(population) %>% 
  top_n(20, avg_coverage) %>% 
  ungroup() %>% 
  mutate(fid = international_id) %>% 
  select(international_id, fid) %>% 
  write_tsv(here::here("data/derived_data/plink_qc/thin_variants/keeplist.20cattle.txt"), col_names = FALSE)
```

### `5cattle`

```{r}
sample_metadata %>% 
  filter(species %in% c("bos primigenius", "bos taurus", "composite", "bos indicus")) %>% 
  group_by(population) %>% 
  top_n(5, avg_coverage) %>% 
  ungroup() %>% 
  mutate(fid = international_id) %>% 
  select(international_id, fid) %>% 
  write_tsv(here::here("data/derived_data/plink_qc/thin_variants/keeplist.5cattle.txt"), col_names = FALSE)
```

```{r}
sample_metadata %>% 
  filter(species %in% c("bos primigenius", "bos taurus")) %>% 
  group_by(population) %>% 
  top_n(5, avg_coverage) %>% 
  ungroup() %>% 
  mutate(fid = international_id) %>% 
  select(international_id, fid) %>% 
  write_tsv(here::here("data/derived_data/plink_qc/thin_variants/keeplist.5taurine.txt"), col_names = FALSE)
```

### `allyak`

```{r}
sample_metadata %>% 
  filter(species %in% c("bos grunniens", "bos mutus")) %>% 
  mutate(fid = international_id) %>% 
  select(international_id, fid) %>% 
  write_tsv(here::here("data/derived_data/plink_qc/thin_variants/keeplist.allyak.txt"), col_names = FALSE)

```

### `allgaurgayal`

```{r}
sample_metadata %>% 
  filter(species %in% c("bos gaurus", "bos frontalis")) %>% 
  mutate(fid = international_id) %>% 
  select(international_id, fid) %>% 
  write_tsv(here::here("data/derived_data/plink_qc/thin_variants/keeplist.allgaurgayal.txt"), col_names = FALSE)
```

### `allbanteng`

```{r}
sample_metadata %>% 
  filter(species %in% c("bos javanicus")) %>% 
  mutate(fid = international_id) %>% 
  select(international_id, fid) %>% 
  write_tsv(here::here("data/derived_data/plink_qc/thin_variants/keeplist.allbanteng.txt"), col_names = FALSE)
```

