---
title: "Plink QC/dataset creation"
  html_document:
    toc: true
    toc_depth: 2
    df_print: paged
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
library(readr)
library(magrittr)
library(purrr)
library(dplyr)
library(stringr)
```

# Setup

```{r}
sample_metadata <- 
  read_csv(here::here("data/derived_data/metadata/bovine_demo.sample_metadata.csv")) %>% 
  mutate(international_id = if_else(international_id == "CPC98_Bprimigenius_EnglandDerbyshire_5936", "ancient_derbyshire", international_id))
```

# Dataset key

* Which samples

```{r}
tibble::tribble(
  ~ Name, ~ Description, ~ `k ran`,
  "full", "All species. All available samples.", "1-20",
  "20all", "All species. Up to 20 (ranked by coverage) samples per population label.", "1-20",
  "15randomall", "All species. Up to 15 per species. For cattle, 5 each of African, European, and Asian taurines and indicines.", "-",
  "5regionall", "All species. Up to 5 (ranked by coverage) samples per species per region", "1-20",
  "allcattle", "Bos taurus, B.indicus, B. primigenius, composite. All samples.", "-",
  "20cattle", "Bos taurus, B.indicus, B. primigenius, composite. Up to 20 (ranked by coverage) samples per population label.", "1-20",
  "5cattle", "Bos taurus, B.indicus, B. primigenius, composite. Up to 5 (ranked by coverage) samples per population label.", "1-20",
  "5taurine", "Bos taurus, B. primigenius. Up to 5 (ranked by coverage) samples per population label.", "1-20",
  "allyak", "B. grunniens and B. mutus. All available samples.", "1-10",
  "allgayalgaur", "B. frontalis and B. gaurus. All available samples.", "1-10",
  "allbanteng", "B. javanicus. All available samples.", "1-8"
)
```

* Thinning parameter

```{r}
tibble::tribble(
  ~ Name, ~ Description,
  "superthin", "Randomly retain 0.001% of SNPs from each chromosome",
  "onepercent", "Randomly retain 0.01% of SNPs from each chromosome"
)
```

# Dataset creation

```{r}
sample_metadata %>% 
  group_by(species) %>% 
  tally(sort = TRUE)
```

## `20all`

```{r}
sample_metadata %>% 
  group_by(population) %>% 
  top_n(20, avg_coverage) %>% 
  ungroup() %>% 
  mutate(fid = international_id) %>% 
  select(international_id, fid) %>% 
  write_tsv(here::here("data/derived_data/plink_qc/thin_variants/keeplist.20all.txt"), col_names = FALSE)
```

## `15randomall`


```{r}
set.seed(100)
```


```{r}
seed100 <- sample_metadata %>% 
  filter(!population %in% c("beefmaster", "droughtmaster", "santa gertrudis", "east african zebu")) %>% 
  # Remove problematic jinchuan yaks
  filter(
    !international_id %in% c(
      "UMCUSAF000000202744",
      "UMCUSAM000000202672",
      "UMCUSAF000000202743",
      "UMCUSAF000000202742"
    )
  ) %>% 
  mutate(group = 
           case_when(
             # Bison
             species == "bison bison" ~ 1,
             # Gayal
             species == "bos frontalis" ~ 2,
             # Gaur
             species == "bos gaurus" ~ 3,
             # Banteng
             species == "bos javanicus" ~ 4,
             # Yaks
             species %in% c("bos grunniens", "bos mutus") ~ 5,
             # Ancient 
             species == "bos primigenius" ~ 6,
             # European taurines
             continent == "europe" & species == "bos taurus" ~ 7,
             # African taurines
             continent == "africa" & species == "bos taurus" ~ 8,
             # Asian taurines
             continent == "asia" & species == "bos taurus" ~ 9,
             # Indian indicines
             region %in% c("india and pakistan", "australia", "americas") & species == "bos indicus" ~ 10,
             # Asian indicines 
             continent == "asia" & species == "bos indicus" ~ 11,
             # African indicines
             continent == "africa" & species == "bos indicus" ~ 12,
             # Put African indicines in with rest of composites
             TRUE ~ 13
           )) %>% 
  group_by(group) %>% 
  nest() %>% 
  ungroup() %>% 
  mutate(nkeep = case_when(
    # Bison, 
    group == 1 ~ 9,
    # Gaur
    group == 3 ~ 2,
    # Banteng
    group == 4 ~ 8,
    # ancient
    group == 6 ~ 2,
    # 15 each of gayal, yak, composite
    group %in% c(2, 5, 13) ~ 15,
    # 5 each of euro taurine, afr taurine, asian taurine = 15
    group %in% c(7, 8, 9) ~ 5,
    # 5 each of indian indicine, e. asian indicine, african indicine = 15
    group %in% c(10, 11, 12) ~ 5
  )) %>% 
  mutate(samp = purrr::map2(data, nkeep, sample_n)) %>% 
  select(samp) %>% 
  unnest() %>% 
  mutate(fid = international_id) %>% 
  select(international_id, fid) %>% 
  write_tsv(here::here("data/derived_data/plink_qc/thin_variants/keeplist.20randomall_seed100.txt"), col_names = FALSE)
```


## `5regionall`

```{r}
sample_metadata %>% 
  mutate(
    region = 
      case_when(
        region == "france" ~ "continental europe",
        region == "australia" ~ "americas",
        TRUE ~ region
      )
  ) %>% 
  group_by(region, species) %>% 
  top_n(5, avg_coverage) %>% 
  ungroup() %>%
  arrange(region, species, population) %>% 
  mutate(fid = international_id) %>% 
  select(international_id, fid) %>% 
  write_tsv(here::here("data/derived_data/plink_qc/thin_variants/keeplist.5regionall.txt"), col_names = FALSE)
```

## `allcattle_rootgayal`

```{r}
sample_metadata %>% 
  filter(species %in% c("bos primigenius", "bos taurus", "composite", "bos indicus", "bos frontalis")) %>% 
  mutate(fid = international_id) %>% 
  select(international_id, fid) %>% 
  write_tsv(here::here("data/derived_data/plink_qc/thin_variants/keeplist.allcattle_rootgayal.txt"), col_names = FALSE)

```


## `20cattle`

```{r}
sample_metadata %>% 
  filter(species %in% c("bos primigenius", "bos taurus", "composite", "bos indicus")) %>% 
  group_by(population) %>% 
  top_n(20, avg_coverage) %>% 
  ungroup() %>% 
  mutate(fid = international_id) %>% 
  select(international_id, fid) %>% 
  write_tsv(here::here("data/derived_data/plink_qc/thin_variants/keeplist.20cattle.txt"), col_names = FALSE)
```

## `5cattle`

```{r}
sample_metadata %>% 
  filter(species %in% c("bos primigenius", "bos taurus", "composite", "bos indicus")) %>% 
  group_by(population) %>% 
  top_n(5, avg_coverage) %>% 
  ungroup() %>% 
  mutate(fid = international_id) %>% 
  select(international_id, fid) %>% 
  write_tsv(here::here("data/derived_data/plink_qc/thin_variants/keeplist.5cattle.txt"), col_names = FALSE)
```

## `5taurine`

```{r}
sample_metadata %>% 
  filter(!population %in% "sichuan indigenous") %>% 
  filter(species %in% c("bos primigenius", "bos taurus")) %>% 
  group_by(population) %>% 
  top_n(5, avg_coverage) %>% 
  ungroup() %>% 
  mutate(fid = international_id) %>% 
  select(international_id, fid) %>% 
  write_tsv(here::here("data/derived_data/plink_qc/thin_variants/keeplist.5taurine.txt"), col_names = FALSE)
```

## `allyak`

```{r}
sample_metadata %>% 
  filter(species %in% c("bos grunniens", "bos mutus")) %>% 
  mutate(fid = international_id) %>% 
  select(international_id, fid) %>% 
  write_tsv(here::here("data/derived_data/plink_qc/thin_variants/keeplist.allyak.txt"), col_names = FALSE)

```

## `allgaurgayal`

```{r}
sample_metadata %>% 
  filter(species %in% c("bos gaurus", "bos frontalis")) %>% 
  mutate(fid = international_id) %>% 
  select(international_id, fid) %>% 
  write_tsv(here::here("data/derived_data/plink_qc/thin_variants/keeplist.allgaurgayal.txt"), col_names = FALSE)
```

## `allbanteng`

```{r}
sample_metadata %>% 
  filter(species %in% c("bos javanicus")) %>% 
  mutate(fid = international_id) %>% 
  select(international_id, fid) %>% 
  write_tsv(here::here("data/derived_data/plink_qc/thin_variants/keeplist.allbanteng.txt"), col_names = FALSE)
```

