rules: ['structure', 'structure_ml']

plink_module: "plink/plink-1.90b"

plink_nt: 12

chr: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', 'X', 'Y']

thin_p: ['onepercent']

dataset: ['20all', '20cattle', '5cattle', 'allyak', 'allgaurgayal', 'allbanteng', '5regionall']

k: {'full':['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20'], '20all':['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20'], '20cattle':['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20'], '5regionall':['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'],
'5cattle':['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20'], 'allyak':['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'], 'allgaurgayal':['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'], 'allbanteng':['1', '2', '3', '4', '5', '6', '7', '8']}
