rules: ["index_map", "extract_850K", "index_850K", "dups_plink", "find_dups"]

ref_genome: "/storage/hpc/group/UMAG/REF_GENOME/ARS-UCD1.2_Btau5.0.1Y.fa"

java_module: "java/openjdk/java-1.8.0-openjdk"

extract_850K_gc: 2

extract_850K_nt: 6

bcftools_module: "bcftools"

gatk_path: "/cluster/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/gatk-3.8-1-0-gf15c1c3ef-qlqslekqpddmxmnfad2uk6s7zrbtfrza/bin/GenomeAnalysisTK.jar"

map: "data/raw_data/850K_snps.tsv"

full_file: "data/derived_data/joint_genotyping/bovine_demo.snps.vcf.gz"

extract_850K_nt: 12

index_850K_nt: 12

plink_nt: 12

king_path: "source_functions/king"

king_nt: 12
