#### PATHS, MODULES, ETC. ####

chr: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', 'X', 'Y']

ref_genome: "/storage/hpc/group/UMAG/REF_GENOME/ARS-UCD1.2_Btau5.0.1Y.fa"

truth_file: "/storage/hpc/group/UMAG/SNP/9913/1kbulls_ars1.2/190923_ALL.sorted.vcf.gz"

850K_map: "data/raw_data/850K_snps.tsv"

java_module: "java/openjdk/java-1.8.0-openjdk"

bcftools_module: "bcftools"

gatk_path: "/cluster/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/gatk-3.8-1-0-gf15c1c3ef-qlqslekqpddmxmnfad2uk6s7zrbtfrza/bin/GenomeAnalysisTK.jar"

picard_module: "picard-tools/picard-2.7.1"

picard_path: "/cluster/software/picard/picard-2.7.1/picard.jar"

king_path: "source_functions/king"

r_module: "r/r-3.4.2"

plink_module: "plink/plink-1.90b"

shapeit_module: "shapeit/shapeit-2r837"

#### joint_genotyping ####

joint_genotyping_rules: ["combine_gvcfs", "genotype_gvcfs_list", "genotype_gvcfs", "select_variants", "variant_filtration", "remove_failed"]

cohort : ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '30', '31', '32', '33']

combine_gvcfs_gc: 4

combine_gvcfs_xmx: 22

genotype_gvcfs_gc: 4

genotype_gvcfs_xmx: 100

genotype_gvcfs_nt: 15

select_variants_nt: 6

select_variants_gc: 2

variant_filtration_gc: 2

variant_filtration_xmx: 20

variant_filter: "-filter 'QD < 7.0' --filterName 'QD7' -filter 'FS > 60.0' --filterName 'FS60' -filter 'MQ < 15.0' --filterName 'MQ15'"

validate_variants_gc: 2

validate_variants_xmx: 12

#### find_dups ####

find_dups_rules: ["targets_file", "extract_850K", "index_850K", "make_bed", "merge_list", "merge_bed", "find_dups"]

index_850K_nt: 4

make_bed_nt: 12

merge_bed_nt: 36

king_nt: 12

#### post_process ####

post_process_rules: ["remove_samples", "collect_metrics", "validate_variants"]

collect_metrics_nt: 8

collect_metrics_gc: 2

collect_metrics_xmx: 24

#### sex_imputation ####

sex_imputation_rules: ["guess_ploidy", "plink_impute_sex"]

tag: ["GT", "PL"]

plink_nt: 12

pab: 133300518

#### phasing ####

phasing_rules: ["snp_positions", "phasing_qc", "phasing_qc_x", "phasing_qc_y", "shapeit_sex_check", "phase_autosomes", "phase_x", "phase_y"]

genetic_map: "data/raw_data/placeholder.map"

imputed_sexes: "data/derived_data/joint_genotyping/impute_sex/imputed_sexes.txt"

geno_filter: 0.10

shapeit_nt: 12
