rules: ["combine_gvcfs", "genotype_gvcfs_list", "genotype_gvcfs", "biallelic_28", "table_28", "table_gf_28", "select_variants", "variant_filtration"]

cohort : ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '30', '31', '32', '33']

chr: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', 'X', 'Y']

ref_genome: "/storage/hpc/group/UMAG/REF_GENOME/ARS-UCD1.2_Btau5.0.1Y.fa"

java_module: "java/openjdk/java-1.8.0-openjdk"

gatk_path: "/cluster/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/gatk-3.8-1-0-gf15c1c3ef-qlqslekqpddmxmnfad2uk6s7zrbtfrza/bin/GenomeAnalysisTK.jar"

combine_gvcfs_gc: 4

combine_gvcfs_xmx: 95

genotype_gvcfs_gc: 4

genotype_gvcfs_xmx: 175

genotype_gvcfs_nt: 24

biallelic_28_nt: 6

select_variants_nt: 6

select_variants_gc: 2

select_variants_xmx: 95

variant_filtration_gc: 6

variant_filtration_xmx: 24

filter: "-filter 'QD < 20.0' --filterName 'QD20' -filter 'FS > 60.0' --filterName 'FS60' -filter 'MQ < 15.0' --filterName 'MQ15' -filter 'MQRankSum < -12.5' --filterName 'MQRankSum-12.5' -filter 'ReadPosRankSum < -8.0' --filterName 'ReadPosRankSum-8'"

bcftools_module: "bcftools"

concat_sort_nt: 12

samtools_module: "samtools/samtools-1.7"

htslib_module: "htslib/htslib-1.7"
