rules: ["combine_gvcfs", "genotype_gvcfs_list", "genotype_gvcfs", "select_variants", "info_filtration", "remove_failed", "format_filtration", "concat_list", "concat"]

cohort : ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '30', '31', '32', '33']

chr: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', 'X', 'Y']

ref_genome: "/storage/hpc/group/UMAG/REF_GENOME/ARS-UCD1.2_Btau5.0.1Y.fa"

java_module: "java/openjdk/java-1.8.0-openjdk"

gatk_path: "/cluster/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/gatk-3.8-1-0-gf15c1c3ef-qlqslekqpddmxmnfad2uk6s7zrbtfrza/bin/GenomeAnalysisTK.jar"

combine_gvcfs_gc: 4

combine_gvcfs_xmx: 95

genotype_gvcfs_gc: 4

genotype_gvcfs_xmx: 175

genotype_gvcfs_nt: 24

select_variants_nt: 6

select_variants_gc: 2

info_filtration_gc: 6

info_filtration_xmx: 24

info_filter: "-filter 'QD < 7.0' --filterName 'QD7' -filter 'FS > 60.0' --filterName 'FS60' -filter 'MQ < 15.0' --filterName 'MQ15'"

format_filter: "'FORMAT/DP >= 8 && FORMAT/GQ >= 20'"

format_filtration_nt: 6

bcftools_module: "bcftools"

samtools_module: "samtools/samtools-1.7"

concat_nt: 12

htslib_module: "htslib/htslib-1.9"
