rules: ['recode_input', 'create_par', 'smartpca']

plink_module: "plink/plink-1.90b"

plink_nt: 12

eigensoft_module: "eigensoft/eigensoft-7.2.1"

chr: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', 'X', 'Y']

thin_p: ['superthin']

dataset: ['allyak', 'allgaurgayal', 'allbanteng', 'projectfull', 'project20all', 'project20cattle']

dataset_key: {'allyak':['allyak'], 'allgaurgayal':['allgaurgayal'], 'allbanteng':['allbanteng'], 'projectfull':['full'], 'project20all':['20all'], 'project20cattle':['20cattle'], 'project5cattle':['5cattle'],}
