rules: ['define_cluster', 'write_cluster', 'freq', 'plink2tm', 'treemix_base', 'treemix']

plink_module: "plink/plink-1.90b"

plink_nt: 12

r_module: "r/r-3.4.2"

python_module: "python/python-2.7.13"

thin_p: ['onepercent']

dataset: ['full']

root: "AmericanBison"

min_m: 1

max_m: 11

ld_snps: 1000
